-- الطبقة النهائية: نسخ المحتوى، سجل العمليات، ملاحظات الأعضاء وموضع الوسائط.
-- شغّل هذا الملف بعد owner_roles_drafts.sql.

create table if not exists public.site_content_versions (
  id bigint generated by default as identity primary key,
  content_id text not null default 'main',
  payload jsonb not null default '{}'::jsonb,
  changed_by uuid references auth.users(id) on delete set null,
  change_note text not null default 'تحديث محتوى',
  created_at timestamptz not null default now()
);

create index if not exists site_content_versions_created_at_idx on public.site_content_versions (created_at desc);
alter table public.site_content_versions enable row level security;

create or replace function public.snapshot_site_content()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  insert into public.site_content_versions (content_id, payload, changed_by, change_note)
  values (old.id, old.payload, auth.uid(), 'نسخة تلقائية قبل النشر');
  return new;
end;
$$;

drop trigger if exists site_content_version_before_update on public.site_content;
create trigger site_content_version_before_update before update on public.site_content
for each row execute function public.snapshot_site_content();

drop policy if exists "admins can read content versions" on public.site_content_versions;
create policy "admins can read content versions" on public.site_content_versions for select to authenticated using (public.is_site_admin());

create or replace function public.list_site_content_versions(limit_count integer default 20)
returns table(id bigint, changed_by uuid, change_note text, created_at timestamptz)
language sql stable security definer set search_path = public
as $$
  select v.id, v.changed_by, v.change_note, v.created_at from public.site_content_versions v
  where public.is_site_admin() and v.content_id = 'main'
  order by v.created_at desc limit least(greatest(coalesce(limit_count, 20), 1), 100);
$$;

create or replace function public.restore_site_content_version(version_id bigint)
returns boolean language plpgsql security definer set search_path = public
as $$
declare version_payload jsonb;
begin
  if not public.is_site_admin() then return false; end if;
  select payload into version_payload from public.site_content_versions where id = version_id and content_id = 'main';
  if version_payload is null then return false; end if;
  update public.site_content set payload = version_payload, updated_at = now() where id = 'main';
  return true;
end;
$$;

grant execute on function public.list_site_content_versions(integer) to authenticated;
grant execute on function public.restore_site_content_version(bigint) to authenticated;

create table if not exists public.site_audit_log (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id) on delete set null,
  action text not null,
  target text not null default 'site',
  detail text not null default '',
  created_at timestamptz not null default now()
);

alter table public.site_audit_log enable row level security;
create index if not exists site_audit_log_created_at_idx on public.site_audit_log (created_at desc);

create or replace function public.write_site_audit(action_name text, target_name text default 'site', detail_text text default '')
returns void language plpgsql security definer set search_path = public
as $$
begin
  if not public.is_site_admin() then return; end if;
  insert into public.site_audit_log (actor_id, action, target, detail)
  values (auth.uid(), left(action_name, 80), left(coalesce(target_name, 'site'), 120), left(coalesce(detail_text, ''), 500));
end;
$$;

create or replace function public.list_site_audit(limit_count integer default 40)
returns table(id bigint, actor_id uuid, action text, target text, detail text, created_at timestamptz)
language sql stable security definer set search_path = public
as $$
  select id, actor_id, action, target, detail, created_at from public.site_audit_log
  where public.is_site_admin() order by created_at desc limit least(greatest(coalesce(limit_count, 40), 1), 100);
$$;

grant execute on function public.write_site_audit(text, text, text) to authenticated;
grant execute on function public.list_site_audit(integer) to authenticated;

create table if not exists public.member_notes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  content_id text not null,
  body text not null default '',
  updated_at timestamptz not null default now(),
  unique (user_id, content_id)
);

create table if not exists public.member_media_progress (
  user_id uuid not null references auth.users(id) on delete cascade,
  content_id text not null,
  seconds numeric not null default 0,
  duration numeric not null default 0,
  updated_at timestamptz not null default now(),
  primary key (user_id, content_id)
);

alter table public.member_notes enable row level security;
alter table public.member_media_progress enable row level security;

drop policy if exists "members manage own notes" on public.member_notes;
create policy "members manage own notes" on public.member_notes for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
drop policy if exists "members manage own media progress" on public.member_media_progress;
create policy "members manage own media progress" on public.member_media_progress for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "member can update own profile" on public.site_members;
create policy "member can update own profile" on public.site_members for update to authenticated using (id = auth.uid()) with check (id = auth.uid());
