-- جدول تسجيل الاهتمام بالمجالس
create table if not exists public.majlis_interest (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) between 1 and 120),
  contact text not null check (char_length(trim(contact)) between 3 and 200),
  created_at timestamptz not null default now()
);

alter table public.majlis_interest enable row level security;

drop policy if exists "anyone can submit majlis interest" on public.majlis_interest;
create policy "anyone can submit majlis interest"
on public.majlis_interest for insert
to anon, authenticated
with check (true);

drop policy if exists "owner can read majlis interest" on public.majlis_interest;
create policy "owner can read majlis interest"
on public.majlis_interest for select
to authenticated
using (lower(auth.jwt() ->> 'email') = lower('owner@example.com'));

drop policy if exists "owner can delete majlis interest" on public.majlis_interest;
create policy "owner can delete majlis interest"
on public.majlis_interest for delete
to authenticated
using (lower(auth.jwt() ->> 'email') = lower('owner@example.com'));
