-- حسابات الأعضاء وإشعارات المالك.
-- استبدل owner@example.com ببريد حساب المالك الموجود لديك قبل التشغيل.

create table if not exists public.site_members (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  full_name text not null default '',
  country_code text not null default 'UN',
  country_name text not null default 'غير محدد',
  created_at timestamptz not null default now()
);

alter table public.site_members add column if not exists country_code text not null default 'UN';
alter table public.site_members add column if not exists country_name text not null default 'غير محدد';

create table if not exists public.site_notifications (
  id bigint generated by default as identity primary key,
  kind text not null default 'general',
  title text not null,
  detail text not null default '',
  created_at timestamptz not null default now(),
  read_at timestamptz
);

create table if not exists public.member_learning (
  user_id uuid primary key references auth.users(id) on delete cascade,
  saved text[] not null default '{}',
  completed text[] not null default '{}',
  updated_at timestamptz not null default now()
);

alter table public.site_members enable row level security;
alter table public.site_notifications enable row level security;
alter table public.member_learning enable row level security;

drop policy if exists "owner can read site members" on public.site_members;
create policy "owner can read site members"
on public.site_members for select
to authenticated
using (lower(auth.jwt() ->> 'email') = lower('owner@example.com'));

drop policy if exists "member can read own profile" on public.site_members;
create policy "member can read own profile"
on public.site_members for select
to authenticated
using (id = auth.uid());

drop policy if exists "owner can read notifications" on public.site_notifications;
create policy "owner can read notifications"
on public.site_notifications for select
to authenticated
using (lower(auth.jwt() ->> 'email') = lower('owner@example.com'));

drop policy if exists "owner can update notifications" on public.site_notifications;
create policy "owner can update notifications"
on public.site_notifications for update
to authenticated
using (lower(auth.jwt() ->> 'email') = lower('owner@example.com'))
with check (lower(auth.jwt() ->> 'email') = lower('owner@example.com'));

drop policy if exists "owner can delete notifications" on public.site_notifications;
create policy "owner can delete notifications"
on public.site_notifications for delete
to authenticated
using (lower(auth.jwt() ->> 'email') = lower('owner@example.com'));

drop policy if exists "member can read own learning" on public.member_learning;
create policy "member can read own learning"
on public.member_learning for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "member can insert own learning" on public.member_learning;
create policy "member can insert own learning"
on public.member_learning for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists "member can update own learning" on public.member_learning;
create policy "member can update own learning"
on public.member_learning for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

create or replace function public.is_site_owner()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select lower(coalesce(auth.jwt() ->> 'email', '')) = lower('owner@example.com');
$$;

grant execute on function public.is_site_owner() to anon, authenticated;

create or replace function public.get_site_country_stats()
returns table(country_code text, country_name text, member_count bigint)
language sql
stable
security definer
set search_path = public
as $$
  select sm.country_code, sm.country_name, count(*)::bigint as member_count
  from public.site_members sm
  where sm.country_code <> 'UN' and sm.country_name <> 'غير محدد'
  group by sm.country_code, sm.country_name
  order by member_count desc, sm.country_name asc;
$$;

grant execute on function public.get_site_country_stats() to anon, authenticated;

create or replace function public.handle_site_user_created()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.site_members (id, email, full_name, country_code, country_name)
  values (
    new.id,
    coalesce(new.email, ''),
    coalesce(new.raw_user_meta_data ->> 'full_name', ''),
    coalesce(nullif(new.raw_user_meta_data ->> 'country_code', ''), 'UN'),
    coalesce(nullif(new.raw_user_meta_data ->> 'country_name', ''), 'غير محدد')
  )
  on conflict (id) do update set
    email = excluded.email,
    full_name = excluded.full_name,
    country_code = excluded.country_code,
    country_name = excluded.country_name;

  insert into public.site_notifications (kind, title, detail)
  values ('account', 'عضو جديد سجّل في الموقع', coalesce(new.email, 'حساب بدون بريد ظاهر'));

  return new;
end;
$$;

drop trigger if exists on_site_user_created on auth.users;
create trigger on_site_user_created
after insert on auth.users
for each row execute function public.handle_site_user_created();

create or replace function public.notify_site_owner()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if TG_TABLE_NAME = 'newsletter_subscribers' then
    insert into public.site_notifications (kind, title, detail)
    values ('newsletter', 'اشتراك جديد في النشرة', new.email);
  elsif TG_TABLE_NAME = 'majlis_interest' then
    insert into public.site_notifications (kind, title, detail)
    values ('majlis', 'طلب اهتمام جديد بالمجلس', new.name || ' · ' || new.contact);
  end if;
  return new;
end;
$$;

drop trigger if exists on_newsletter_subscriber_created on public.newsletter_subscribers;
create trigger on_newsletter_subscriber_created
after insert on public.newsletter_subscribers
for each row execute function public.notify_site_owner();

drop trigger if exists on_majlis_interest_created on public.majlis_interest;
create trigger on_majlis_interest_created
after insert on public.majlis_interest
for each row execute function public.notify_site_owner();

create index if not exists site_notifications_created_at_idx on public.site_notifications (created_at desc);
create index if not exists site_members_created_at_idx on public.site_members (created_at desc);
