-- جدول المشتركين في النشرة البريدية
create table if not exists public.newsletter_subscribers (
  id bigint generated by default as identity primary key,
  email text not null unique check (email ~* '^[^@\s]+@[^@\s]+\.[^@\s]+$'),
  created_at timestamptz not null default now()
);

alter table public.newsletter_subscribers enable row level security;

drop policy if exists "anyone can subscribe to newsletter" on public.newsletter_subscribers;
create policy "anyone can subscribe to newsletter"
on public.newsletter_subscribers for insert
to anon, authenticated
with check (true);

drop policy if exists "owner can read newsletter subscribers" on public.newsletter_subscribers;
create policy "owner can read newsletter subscribers"
on public.newsletter_subscribers for select
to authenticated
using (lower(auth.jwt() ->> 'email') = lower('owner@example.com'));

drop policy if exists "owner can delete newsletter subscribers" on public.newsletter_subscribers;
create policy "owner can delete newsletter subscribers"
on public.newsletter_subscribers for delete
to authenticated
using (lower(auth.jwt() ->> 'email') = lower('owner@example.com'));
