-- إحصائيات الزيارات والتحميلات والاستماع.
-- شغّل هذا الملف بعد owner_roles_drafts.sql.

create table if not exists public.site_events (
  id bigint generated by default as identity primary key,
  event_name text not null,
  path text not null default '/',
  visitor_id text not null default '',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.site_events enable row level security;
create index if not exists site_events_created_at_idx on public.site_events (created_at desc);
create index if not exists site_events_name_path_idx on public.site_events (event_name, path);

create or replace function public.track_site_event(
  p_event_name text,
  p_path text default '/',
  p_visitor_id text default '',
  p_metadata jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if trim(coalesce(p_event_name, '')) = '' then return; end if;
  insert into public.site_events (event_name, path, visitor_id, metadata)
  values (left(trim(p_event_name), 40), left(coalesce(nullif(trim(p_path), ''), '/'), 240), left(coalesce(p_visitor_id, ''), 120), coalesce(p_metadata, '{}'::jsonb));
end;
$$;

grant execute on function public.track_site_event(text, text, text, jsonb) to anon, authenticated;

create or replace function public.get_site_analytics(p_days integer default 30)
returns table(metric text, value bigint, label text)
language sql
stable
security definer
set search_path = public
as $$
  with windowed as (
    select * from public.site_events
    where public.is_site_admin()
      and created_at >= now() - make_interval(days => least(greatest(coalesce(p_days, 30), 1), 365))
  )
  select 'page_views'::text, count(*)::bigint, 'زيارات الصفحات'::text from windowed where event_name = 'page_view'
  union all select 'unique_visitors'::text, count(distinct nullif(visitor_id, ''))::bigint, 'زوار فريدون'::text from windowed where event_name = 'page_view'
  union all select 'downloads'::text, count(*)::bigint, 'تحميلات'::text from windowed where event_name = 'download'
  union all select 'media_plays'::text, count(*)::bigint, 'مرات الاستماع والمشاهدة'::text from windowed where event_name = 'media_play'
  union all (select 'top_path'::text, count(*)::bigint, left(path, 120)::text from windowed where event_name = 'page_view' group by path order by count(*) desc limit 10);
$$;

grant execute on function public.get_site_analytics(integer) to authenticated;

